# 配置参考：https://github.com/SpringForAll/spring-boot-starter-swagger
swagger:
  enabled: true
  title: 虹雨电商门户接口文档
  description: 虹雨电商门户SpringCloud接口文档
  contact:
    name: vigo

# 数据源
spring:
  # redis 相关
  redis:
#    host: 127.0.0.1
    host: 119.45.147.179
    port: 6379
    password: 123456
  rabbitmq:
    host: 119.45.147.179
    port: 5672
    virtual-host: rainbow
    username: rainbow
    password: rainbow
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
    template:
      receive-timeout: 30000
      reply-timeout: 30000
      retry:
        enabled: false
      listener:
        direct:
          retry:
            enabled: false
        default-requeue-rejected: true
        retry:
          enabled: false
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: admin
    dynamic:
      primary: goods
      druid: # 2.2.3开始提供全局druid参数，以下是默认值和druid原生保持一致
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 10000
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 18800
        validation-query: select 1
        validation-query-timeout: 20000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      datasource:
        admin:
          username: root
          password: mysql
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://119.45.147.179:3306/vvshop_user?useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#          url: jdbc:mysql://127.0.0.1:3306/vvshop_user?useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
          initialSize: 5
          minIdle: 5
          maxActive: 20
        goods:
          username: root
          password: mysql
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://119.45.147.179:3306/vvshop_goods?useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#          url: jdbc:mysql://127.0.0.1:3306/vvshop_goods?useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
          initialSize: 5
          minIdle: 5
          maxActive: 20



store:
  qiniu:
    accessKey: uzRSzrJlUGa_e_Z77AvkcGMYSmo1oyxlRG9luQ3-
    secretKey: LuTVBTq1N9j8tGFRbJVTk0YYqvwZWD6SektFsjIz
    domain: https://image.songshupinpin.com
    bucket: songshu-online


rainbow:
  alipay:
    appId: 2016102300747212
    merchantPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCjeWy4ozel0vDna5vo13j9SFt+PSsAWb0MwZgsY8skXto3dcB7HabohLRt4sTukc/F3y3QtqEgXnEzwtY94wn5Aus470f5Y1rwugXQm+hiygBHgxED8Y0PNs7RpvqBW0+TFNNN2DYi1rGQ39q3iXHMZYqaKKi9aJ/ZL0xGUEUNztF0OabdXTvcnbrC7RK86UU8iFPvjcJ5jbZO8CecIjuIpM/R6PTiaNFNW5FtJAB7n/kH5hYrSsee1RmyY359GdL/X7tV2JB2von1CccKk+YH/y3MX67W4VFJeDlV48weecI0keeKWOXdraAf7QAPvzbM+19emILqk/sU5z2gkw1fAgMBAAECggEBAIfGMiaoaW+w46VSGwwo6rRzhIo1A6Im5n3RzTIRMIfkwBmQE24uEpLMpY8e6bG8KXWPB95x0SGxTxROnuKHz6Cia/u9wWnAu6d02Z+J3lkurUy370n3NdGNE/nNVgJadJ0Ujuv4x/3nk1NgmagW4A2DyLqBSqUGYL1iK1e7E5+C8A/5Ne89WQDApJFXZJYFtypP23/ANieD1GiMd6e99eCG1U5tItqjWXFQrrNwyh/1UcQUFnJcdxPYKTboIl483KKVF+PGmLejlydGjmgMNitwCAsxE7AUBVJYVG1u9UF9XvU9OpuKEopI09Lykfhi2Ct+wsvRS0of8noByIYHHQECgYEA6z4q68kd/qTKDa28p+RUTjdNSB0Ch8SOw3Ng6Oc1mi52ohfKU5lxRviOr/D95V+dwK8KVKKOL8Fq04Wn/wwKbgeZ0RwcPafsxLbHLHvO1Za7beYM/iLf1jR0UAE97qtyY0A17VjyVPUh3MR/y7jCAm99hnr+3xL2WEY/lsUybsUCgYEAseYZPOusAvvOr0F0fZhrqn2/dWZa0N6P5ihPbp8ADlI4KM+hLrfbJud9arim8fG4itocMhPcJ11rMOInSYhkJlzTVd3JlXzQfzWxRQFTS3pD9YAD+/KT0PzLvkK490IHXmpedhaW9fLNPUgh7nTXM2UPKahb+hmh3a5aSHT2zdMCgYBDfw7poEcO7VFcI2Fh+s2Fs7Bk5I35Tph30/8WVGC44GQBljnjSr+J0X9/U/JFge3Nf2vDZPDPGvv/vPW65EWJ1Hx510rzFd+FgbwcM1nhRuJ4Ye2QbYkz+ND2s6SFeoPTnnTaqQ6++abBpU/VsClacYreryO59cLhCSbtp58U0QKBgQCW/BlTcRnOdnSWndEGf4RxcMQ8GaDeQOaUioXP9zaO8Q0k5gOAqR5gyHvTReC621Kq1i6z+dMRveGp3WdGq3GEdagP6mqaaxJxxNotHNDa8GwZQosfHGSELOmnEu31PJ8QbOq7ArUhDO9QIZZa0eOLhSv3SSK3A2YzxTRu5oZJbQKBgQCGrSMljctK8TDPdqTCRGabE4rEhiw9yU3SkaXweOrEbQKR5o0nOsVPFfChA5opoDIioTHrBbai4NG7CLcdA93YmKemMOQbTY1ieCcGiNDujGj9v/X+kW6MQ0CAWaeLK6+V7Eo/Gf5glucfO7TOKzz5ftibqe5r0gk/csTV0hrBLg==
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo+bD8mRvKxUy5+aisWEJGMG4Fi5Jjo69aGjvQtcSrZURntK7tZZyYsO3hTlp37qzlN+LQTCzZScPMF+I9iKrJ74/CVEJGy9EZglzPT+9raDIctcLCS0YJx6/Ys/6+Ii1vtnDWJw7+/PQLDqf1PEBNU/tGC6ru+BHd9OpbQVbI+h7jsj9FNUXJH+6xCbK7GENi/CnIaC4I9O56PmrwXusSWRhtcB5aZSuUiwWb623c8uhnmxkpORL5gHygzKaOewxrHKw+qbo0kNkruLaBy/px0sqn0XPhRC8AVWC83wseei2N3cPCRJwcyB+skeMKzgd2EQMRPATWbTV3jX1W9P1AwIDAQAB
    notifyUrl: http://localhost:8099/alipay/aliPayNotify
    returnUrl: http://localhost:8800/payDone
    signType: RSA2
    charset: utf-8
    gatewayUrl: https://openapi.alipaydev.com/gateway.do