# 配置参考：https://github.com/SpringForAll/spring-boot-starter-swagger
swagger:
  enabled: true
  title: 虹雨电商接口文档
  description: 虹雨电商SpringCloud接口文档
  contact:
    name: vigo

# 数据源
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: admin
    dynamic:
      primary: admin
      druid: # 2.2.3开始提供全局druid参数，以下是默认值和druid原生保持一致
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 10000
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 18800
        validation-query: select 1
        validation-query-timeout: 20000
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      datasource:
        admin:
          username: root
          password: mysql
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/vvshop_user?useSSL=false&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
          initialSize: 5
          minIdle: 5
          maxActive: 20


