# 配置参考：https://github.com/SpringForAll/spring-boot-starter-swagger
swagger:
  enabled: true
  title: 虹雨电商接口文档
  description: 虹雨电商SpringCloud接口文档
  contact:
    name: vigo

# 数据源
hikari:
  user:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/vvshop_user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: root
    password: mysql
    maximum-pool-size: 80
    pool-name: user
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1765000
    minimum-idle: 5


